basePath: '{{.BasePath}}'
host: '{{.Host}}'
info:
  contact: {}
  description: An example of gin
  license: {}
  title: Golang Gin API
  version: "1.0"
paths:
  /user/info:
    get:
      consumes:
      - application/json
      description: 获取指定ID记录
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
  /user/list:
    get:
      consumes:
      - application/json
      description: 获取所有用户
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
swagger: "2.0"
